import {
  Users,
  UserPlus,
  User,
  Phone,
  LayoutDashboard,
  Kanban,
  FileText,
  FileBarChart,
  LogOut,
  Sun,
  Moon,
  Menu,
  X,
  Copy,
  Check,
  ChevronDown,
  Upload,
  Building2,
  Shield,
  Plus,
  Briefcase,
  LogIn,
  FileDown,
  Search,
  AlertTriangle,
  Wrench,
  Layers,
  Scissors,
  GripVertical,
  Hash,
  Stamp,
  EyeOff,
  Minimize2,
  ScanText,
  Image,
  FolderUp,
  ClipboardList,
  IdCard,
  Table2,
  MessageSquare,
  MessageCircle,
  Send,
  RotateCw,
  LifeBuoy,
  LayoutList,
  Bug,
  Lightbulb,
  ClipboardPen,
  CircleDot,
  Clock,
  PlayCircle,
  Eye,
  Lock,
  Archive,
  ChevronRight,
  ChevronLeft,
  Flag,
  ArrowDown,
  ArrowUp,
  Minus,
  Trash2,
  Bell,
  Camera,
  ScanFace,
  Download,
  Printer,
  Scale,
  Mail,
  Keyboard,
  type LucideIcon,
} from "lucide-react";

const icons = {
  users: Users,
  userPlus: UserPlus,
  user: User,
  dashboard: LayoutDashboard,
  kanban: Kanban,
  fileText: FileText,
  reports: FileBarChart,
  logOut: LogOut,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  x: X,
  copy: Copy,
  check: Check,
  chevronDown: ChevronDown,
  upload: Upload,
  building: Building2,
  shield: Shield,
  plus: Plus,
  briefcase: Briefcase,
  logIn: LogIn,
  fileDown: FileDown,
  search: Search,
  alert: AlertTriangle,
  wrench: Wrench,
  layers: Layers,
  scissors: Scissors,
  grip: GripVertical,
  hash: Hash,
  stamp: Stamp,
  eyeOff: EyeOff,
  minimize: Minimize2,
  scanText: ScanText,
  image: Image,
  folderUp: FolderUp,
  clipboardList: ClipboardList,
  idCard: IdCard,
  table: Table2,
  messageSquare: MessageSquare,
  messageCircle: MessageCircle,
  send: Send,
  rotateCw: RotateCw,
  ticket: LifeBuoy,
  list: LayoutList,
  bug: Bug,
  lightbulb: Lightbulb,
  clipboardPen: ClipboardPen,
  circleDot: CircleDot,
  clock: Clock,
  play: PlayCircle,
  eye: Eye,
  lock: Lock,
  archive: Archive,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  flag: Flag,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  minus: Minus,
  trash: Trash2,
  bell: Bell,
  camera: Camera,
  scanFace: ScanFace,
  phone: Phone,
  download: Download,
  printer: Printer,
  scale: Scale,
  mail: Mail,
  keyboard: Keyboard,
} as const;

export type IconName = keyof typeof icons;

export function Icon({
  name,
  className = "h-4 w-4 shrink-0",
  strokeWidth = 1.75,
}: {
  name: IconName;
  className?: string;
  strokeWidth?: number;
}) {
  const LucideComp: LucideIcon = icons[name];
  return <LucideComp className={className} strokeWidth={strokeWidth} aria-hidden />;
}
